{
 "title": "fping",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "group",
    "query": "label_values(fping_created,group)"
   },
   {
    "name": "name",
    "query": "label_values(fping_created,name)"
   },
   {
    "name": "address",
    "query": "label_values(fping_created,address)"
   },
   {
    "name": "interval",
    "query": "15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Average ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fping_sum{group=~\"$group\",name=~\"$name\",address=~\"$address\"}[$interval])) by (name)\n/\r\n  sum(rate(fping_count{group=~\"$group\",name=~\"$name\",address=~\"$address\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$name",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(fping_bucket{group=~\"$group\",name=~\"$name\",address=~\"$address\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(meshping_lost{target=~\"$target\",name=~\"$name\"}[$interval]) > 0"
    }
   ]
  }
 ]
}